### ISSUE TITLE
Update markdown-it-attrs dependency

### ISSUE THREAD

**Issue by chaenu** [Sebastian-Fitzner/mangony-hbs-helpers#3]
Hey Sebastian,

there's a bug in markdown-it-attrs v0.5.1, which is fixed in v0.6.0 (see https://github.com/arve0/markdown-it-attrs/issues/5). As in the package.json the version is defined with a tilde and not with a caret, no newer major versions are installed. So how do we get this bugfix into mangony-hbs-helpers? Shall we generally change the tilde to a caret in the package.json or just update the version for markdown-it-attrs?

**Comment by Sebastian-Fitzner** [comment]
In general we should use ~ in our package.json. 

I will publish a new version in a few minutes, so you can update your project. 

Is that okay for you?

**Comment by chaenu** [comment]
Thank you!
