### ISSUE TITLE
getUrl helper fails with picture art direction pattern

### ISSUE THREAD

**Issue by jannicz** [Sebastian-Fitzner/mangony-hbs-helpers#4]
The getUrl helper is designed to prefix a relative url with block.data.root.assets. This method fails when combined with c-picture veams component using the art direction pattern with retina support.

Current output:
`source data-srcset="../../../img/pictures/xyz.jpg 1x, img/pictures/xyz.jpg_2x.jpg 2x"`

Expected output would be:
`source data-srcset="../../../img/pictures/xyz.jpg 1x, ../../../img/pictures/xyz.jpg_2x.jpg 2x"`

The helper fails when a there are multiple urls in the string. Suggestion for improvement:

```
module.exports = function getUrl(str, block) {
	if (!str || typeof str !== 'string') return;
	var externals = [
		'http://',
		'https://',
		'mailto:'
	];

	var parts = str.split('1x,');
	var url = str;

	parts.forEach(function(part) {
		if (!externals.some(function (el) {
				return part.includes(el)
			})) {
			url = url.replace(part, block.data.root.assets + part.replace(/^\s+/, ''));
		}
	});
	return url;
};
```

Same concept but split by '1x,' and trimmed of leading spaces. So far only tested in my prototype. @Sebastian-Fitzner any thoughts?

**Comment by Sebastian-Fitzner** [comment]
Hmm, I think that is the wrong approach. In general the structure of the picture component looks like that: 

```json
"items": [
	{
		"srcset": [
			{
				"src": "http://placehold.it/400x300",
				"imageWidth": "400w"
			}
		]
	}
]
```

Why not use {{imageWidth}} as retinaSupport value? This will look like that:
```json
"items": [
	{
		"srcset": [
			{
				"src": "http://placehold.it/400x300",
				"imageWidth": "1x"
			},
			{
				"src": "http://placehold.it/800x600",
				"imageWidth": "2x"
			}
		]
	}
]
```

Of course you can add a new property to the template itself. I

 wouldn't change the helper for that purpose. The helper has one functionallity: return a string with or without @root.assets as prefix.

So what do you think?

**Comment by jannicz** [comment]
@Sebastian-Fitzner i think you could be right! Thanks! I will try it out monday, you can close the issue.
